server:
  port: 8080
  servlet:
    context-path: /ducmoba

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/test_service"
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto:  update
    show-sql: true

jwt:
  signerKey: "g6211yH41ADh55Tdmfc+OCaFa66l66F8ir9z0MsVRefbN82NkwDcAMUfEilVTIJk"
  valid-duration: 20 #in second
  refreshable-duration: 360

logging:
  level:
    org:
      springframework:
        security: DEBUG





